### ISSUE TITLE
issue: Clarify IdP ms workflow and callback destinations

### ISSUE THREAD

**Issue by ross-little** [EC-SEAL/edugain-idp#1]
# Issue report
It is needed to clarify the workflow of the IdP ms (eduGAIN and eIDAS) and the different callback addresses. The expected behaviour below is done assuming for eIDAS but is essentially the same for eduGAIN. 

We do see that RequestManager still needs some way in how to request authentication or attribute retrieval? 

**Expected Behavior**
1.	Use the ESMO eIDAS IdP ms as base
2.	Initial API trigger:
a.	Update to read the idpRequest and idpMetadata objects from the SM upon reception of: 
i.	/as/authenticate received from Dashboard (due to AuthSource selected)
ii.	/as/authenticate received from RequestManager (due to authentication requested in spRequest… how?)
b.	Update to read the apRequest and apMetadata objects from the SM upon reception of:
i.	/is/query received from Dashboard (due to AttrSource selected)
ii.	/is/query received from RequestManager (due to authentication requested in spRequest… how?))
3.	Update code to check if source of call was Dashboard or from RequestManager ms and save the callback address destination in the SM. 
4.	Build the authentication request to external eIDAS end point as per interface protocol (key cloak) based on idpRequest & idpMetadata or apRequest & apMetadata as per the initial API trigger and provide call back address to eIDAS IdP ms. 
5.	User authenticates and returns identity attributes to the IdP ms.
6.	Update code to check If the source of the call was APIGatewayClient or RequestManager (as per callback address destination previously stored in SM).
a.	If APIGatewayClient store the retrieved eIDAS response attributes in a new dataset in the user´s dataStore in the SM i.e. retrieve datastore from SM and update with new retrieved eIDAS identity attributes, and perform call back to APIGatewayClient ms with /cl/callback. NB Generate unique identifier UUID for the dataSet (to be doubly sure there is no clash it can check the list of identity objects already assigned to the user datastore).
b.	If RequestManager store the retrieved eIDAS response attributes in the dsResponse and eIDAS address in the dsMetadata and perform call back to RequestManager with /rm/response.

**Solution to be agreed**
Agree expected behaviour and update to indicate how RequestManager indiactes authentication or attribute retrieval request.

@faragom @endimion @cbuendia-atos @rcc-atos @mvj66

**Comment by endimion** [comment]
Ok already replied via email but posting my views here as well.

I think that a more appropriate flow that allows for both web and mobile clients to use the SEAL infrastructure would be the following:

1. Client (web/mobile doesn't make a difference) using API GW creates new session
2. Client stores idpRequest & idpMetadata to the session previously created
3. Client stores callback url to the same session
4. Client (via API GW) makes a get request  to the /as/authenticate endpoint
5. IdP ms retrieves request token (msToken) from request
6. IdP ms retrieves sessionId from msToken by calling via API GW the SM (validating the jwt and retrieving the payload)
7. IdP ms retrieves IdPRequest and metadata object from SM (using API GW again)
8. IdP ms makes an appropriate request the IdP (e.g. eIDAS) making sure that a session parameter is given and is associated internally with the sessionId
9. User authenticates at the IdP
10. IdP ms receives the authentication response
11. IdP ms writes to the SM the authentication response using the original sessionId
12. IdP ms redirects to the callback url (of the Client) that was stored with the sessionId, by generating an appropriate msToken
13. Client retrieves the msToken at callback url
14. Client uses msToken to validate it and retrieve user attributes from SM (via API GW)

**Comment by faragom** [comment]
>

> 
> # Issue report
> 
> It is needed to clarify the workflow of the IdP ms (eduGAIN and eIDAS) and the different callback addresses. The expected behaviour below is done assuming for eIDAS but is essentially the same for eduGAIN.
> 
> We do see that RequestManager still needs some way in how to request authentication or attribute retrieval?
> 

There should be different endpoints for both. That's why we have two separate interfaces:

https://github.com/EC-SEAL/interface-specs/blob/master/SEAL_Interfaces.yaml#L1412
https://github.com/EC-SEAL/interface-specs/blob/master/SEAL_Interfaces.yaml#L1450

On the SP side, we can have either separate endpoints, or control it through SP metadata. So, the SP will choose the behaviour, either by calling a specific endpoint or by defining it in its metadata.

> **Expected Behavior**
> 
>     1. Use the ESMO eIDAS IdP ms as base
> 
And the AP ms, which is exacty the same ms but with different naming and slightly different input params (at least the one I did for SAML)

>     2. Initial API trigger:
>        a.	Update to read the idpRequest and idpMetadata objects from the SM upon reception of:
>        i.	/as/authenticate received from Dashboard (due to AuthSource selected)
>        ii.	/as/authenticate received from RequestManager (due to authentication requested in spRequest… how?)

SP metadata or specific endpoint at the SPms

>        b.	Update to read the apRequest and apMetadata objects from the SM upon reception of:
>        i.	/is/query received from Dashboard (due to AttrSource selected)
>        ii.	/is/query received from RequestManager (due to authentication requested in spRequest… how?))
> 

Same

>     3. Update code to check if source of call was Dashboard or from RequestManager ms and save the callback address destination in the SM.
> 

Since we have a callback set call, why don't we make the request manager set the callback address and then the idpms does not care where the request came from?

>     4. Build the authentication request to external eIDAS end point as per interface protocol (key cloak) based on idpRequest & idpMetadata or apRequest & apMetadata as per the initial API trigger and provide call back address to eIDAS IdP ms.
> 
>     5. User authenticates and returns identity attributes to the IdP ms.
> 
>     6. Update code to check If the source of the call was APIGatewayClient or RequestManager (as per callback address destination previously stored in SM).

see previous comment

>        a.	If APIGatewayClient store the retrieved eIDAS response attributes in a new dataset in the user´s dataStore in the SM i.e. retrieve datastore from SM and update with new retrieved eIDAS identity attributes, and perform call back to APIGatewayClient ms with /cl/callback. NB Generate unique identifier UUID for the dataSet (to be doubly sure there is no clash it can check the list of identity objects already assigned to the user datastore).
>        b.	If RequestManager store the retrieved eIDAS response attributes in the dsResponse and eIDAS address in the dsMetadata and perform call back to RequestManager with /rm/response.
> 

Just store them both any time.

> 
> **Solution to be agreed**
> Agree expected behaviour and update to indicate how RequestManager indiactes authentication or attribute retrieval request.
> 
> @faragom @endimion @cbuendia-atos @rcc-atos @mvj66

**Comment by faragom** [comment]
> 
> 
> Ok already replied via email but posting my views here as well.
> 
> I think that a more appropriate flow that allows for both web and mobile clients to use the SEAL infrastructure would be the following:

Difference here is not web/mobile clients, but dashboard-started request or SP-started request

> 
>     1. Client (web/mobile doesn't make a difference) using API GW creates new session
> 
>     2. Client stores idpRequest & idpMetadata to the session previously created

Yes, either the api gw or the request manager do this

> 
>     3. Client stores callback url to the same session

Exactly. Same behaviour for RM and AG
> 
>     4. Client (via API GW) makes a get request  to the /as/authenticate endpoint
> 
>     5. IdP ms retrieves request token (msToken) from request
> 
>     6. IdP ms retrieves sessionId from msToken by calling via API GW the SM (validating the jwt and retrieving the payload)
> 
>     7. IdP ms retrieves IdPRequest and metadata object from SM (using API GW again)
> 
>     8. IdP ms makes an appropriate request the IdP (e.g. eIDAS) making sure that a session parameter is given and is associated internally with the sessionId
> 
>     9. User authenticates at the IdP
> 
>     10. IdP ms receives the authentication response
> 
>     11. IdP ms writes to the SM the authentication response using the original sessionId
> 
>     12. IdP ms redirects to the callback url (of the Client) that was stored with the sessionId, by generating an appropriate msToken
> 
>     13. Client retrieves the msToken at callback url
> 
>     14. Client uses msToken to validate it and retrieve user attributes from SM (via API GW)
